services:
  - type: web
    name: stock-simulator-api
    env: node
    rootDir: server
    buildCommand: npm install --platform=linux --arch=x64
    preDeployCommand: npm rebuild better-sqlite3
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
