services:
  - type: web
    name: stock-simulator-api
    env: node
    rootDir: server
    buildCommand: npm ci
    preDeployCommand: npm rebuild sqlite3
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
